name: Pre-Merge

on:
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run assemble
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run testDebugUnitTest
        run: ./gradlew testDebugUnitTest
      - name: run jacocoTestReport
        run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v3

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run lintDebug
        run: ./gradlew lintDebug
      - name: run detektCheck
        run: ./gradlew detektCheck
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
